name: Visit URL and Notify everyday at 09:30

on:
  schedule:
    - cron: "30 1 * * *"
  workflow_dispatch:

jobs:
  visit-and-notify:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests

    - name: Run script
      run: python visit_and_notify.py
         
    - name: 'Checkout codes'
      uses: actions/checkout@v1
    
    - name: 'Get Weather'
      run: bash ./weather.sh
    
    - name: 'Get Date'
      run: echo "REPORT_DATE=$(TZ=':Asia/Shanghai' date '+%Y-%m-%d %T')" >> $GITHUB_ENV
    
    - name: 'Send mail'
      uses: dawidd6/action-send-mail@master
      with:
          server_address: smtp.qq.com
          server_port: 465
          username: ${{ secrets.MAIL_USERNAME }}
          password: ${{ secrets.MAIL_PASSWORD }}
          subject: 天气预报-陕西-西安 (${{env.REPORT_DATE}})
          html_body: file://result.html
          to: 3409056090@qq.com
          from: GitHub Actions
